use rusqlite::Connection;

pub const ITEM_SUBCLASSES: &[&str] = &[
    "Miscellaneous",
    "Staff",
    "Cloth",
    "Leather",
    "Axe",
    "Sword",
    "Potion",
    "Mace",
    "Quest",
    "Food & Drink",
    "Junk",
    "Meat",
    "Cooking",
    "Mail",
    "Herb",
    "Dagger",
    "Bag",
    "Simple",
    "Parts",
    "Consumable",
    "Shield",
    "Other",
    "Scroll",
    "Book",
    "Mount",
    "Bandage",
    "Polearm",
    "Gun",
    "Quiver",
    "Ammo Pouch",
    "Item Enhancement",
    "Leatherworking",
    "Elixir",
    "Bow",
    "Arrow",
    "Bullet",
    "Alchemy",
    "Tailoring",
    "Key",
    "Metal & Stone",
    "Blacksmithing",
    "Reagent",
    "Fist Weapon",
    "Explosives",
    "Devices",
    "Engineering",
    "Pet",
    "Wand",
    "Enchanting",
    "Fishing Pole",
    "Crossbow",
    "First Aid",
    "Elemental",
    "Plate",
    "Flask",
    "Fishing",
    "Holiday",
    "Jewelcrafting",
    "Soul Bag",
    "Enchanting Bag",
    "Orange",
    "Herb Bag",
    "Totem",
    "Libram",
    "Idol",
    "Prismatic",
    "Green",
    "Red",
    "Purple",
    "Yellow",
    "Blue",
    "Materials",
    "Engineering Bag",
    "Gem Bag",
    "Thrown",
    "Meta",
    "Mining Bag",
    "Exotic",
    "Leatherworking Bag",
];

pub const ITEM_SUBCLASSES_FR: &[&str] = &[
    "Divers",
    "Bâton",
    "Tissu",
    "Cuir",
    "Hache",
    "Épée",
    "Potion",
    "Masse",
    "Quête",
    "Nourriture & boisson",
    "Camelote",
    "Viande",
    "Cuisine",
    "Mailles",
    "Herbe",
    "Dague",
    "Sac",
    "Simple",
    "Parties",
    "Consommable",
    "Bouclier",
    "Autre",
    "Parchemin",
    "Livre",
    "Monture",
    "Bandage",
    "Arme d’hast",
    "Arme à feu",
    "Carquois",
    "Giberne",
    "Amélioration d’objet",
    "Travail du cuir",
    "Élixir",
    "Arc",
    "Flèche",
    "Balle",
    "Alchimie",
    "Couture",
    "Clé",
    "Métal & pierre",
    "Forge",
    "Composant",
    "Arme de pugilat",
    "Explosif",
    "Appareil",
    "Ingénierie",
    "Familier",
    "Baguette",
    "Enchantement",
    "Canne à pêche",
    "Arbalète",
    "Secourisme",
    "Élémentaire",
    "Plaque",
    "Flacon",
    "Pêche",
    "Fête",
    "Joaillerie",
    "Sac d’âme",
    "Sac d’enchanteur",
    "Orange",
    "Sac d’herboriste",
    "Totem",
    "Libram",
    "Idole",
    "Prismatique",
    "Verte",
    "Rouge",
    "Violette",
    "Jaune",
    "Bleue",
    "Matériaux",
    "Sac d’ingénieur",
    "Sac de gemmes",
    "Arme de jet",
    "Méta",
    "Sac de mineur",
    "Exotique",
    "Sac de travailleur du cuir",
];

pub fn create_item_subclass_table(conn: &Connection) -> rusqlite::Result<()> {
    conn.execute(
        "CREATE TABLE IF NOT EXISTS item_subclass (
            id INTEGER PRIMARY KEY,
            label TEXT NOT NULL,
            label_frFR TEXT NOT NULL
        )",
        [],
    )?;
    for (i, (label, label_fr_fr)) in ITEM_SUBCLASSES.iter().zip(ITEM_SUBCLASSES_FR.iter()).enumerate() {
        conn.execute(
            "INSERT INTO item_subclass (id, label, label_frFR) VALUES (?1, ?2, ?3)",
            (i as i32 + 1, *label, *label_fr_fr),
        )?;
    }
    Ok(())
}
